# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22a766de056fedeeedd8d5ae1404fb37871758031b11836f267cc074334273981de85b8d5f03b53a394cac69ea15f0d4facb7d70c50c89341dd0d6f228318839

test:
  secret_key_base: dd969f35d67adde5467f3da0c2bd557c994f36dc833fda7e30c166b83dc335a318a19638821dca505f40bc4949f2ae856b608ea269afa4030f16af4565f4737e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
